language: java

services:
  - docker

   env:
     global:
       - GCP_PROJECT_ID=devops-2020-295414
       - IMAGE=gcr.io/devops-2020-295414/devops-exam
       - CLOUD_RUN_SERVICE=devops-2020-295414
       - CLOUD_RUN_REGION=us-central1
       - CLOUDSDK_CORE_DISABLE_PROMPTS=1
       -
  before_install:
  - openssl aes-256-cbc -K $encrypted_6c1e51b8473d_key -iv $encrypted_6c1e51b8473d_iv -in devops-2020-295414-205a969fb1df.json.enc -out devops-2020-295414-205a969fb1df.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=devops-2020-295414-205a969fb1df.json
  - gcloud auth configure-docker
  - gcloud config set project "${GCP_PROJECT_ID}"
  - gcloud componenets install beta

install: true # no-op

script:
  - |
    set -ex;
    docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
    docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
    set +x


before_install:
  - chmod +x mvnw