---
env:
  global:
    - GCP_PROJECT_ID=devops-2020-29541
    - IMAGE=gcr.io/devops-2020-295414/devops-exam
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - CLOUD_RUN_SERVICE=devops-2020-295414
    - CLOUD_RUN_REGION=us-central1
    -
      secure: EMEGDhmmKoAKBmERSG68P2BGkB17edtFDGuDSE9tqNJMKt5MaSf0P2oXuk7zzNuVjvwCl5hJELnm539O/gC3m8A25hm3rDFOO05ab7b+RWKVjpkXPeTnUkKKHt8drFoHmFDbstDZjOHSGm+PUbXGSvX4qsn+rfjmDrT/GFGP+0ICNLG8ReMGsm+ZCI5BXi7vWVUKHeuhGVrSqsGofx4w9YcH96nro9dQvVfl3ZZb66enFHW7rTEje2bL7GgqLVMCCtm7o/N1kWHz87w9YCX36bQRGW8yi1YtFZNZzQ928C/xWKCJQvAzLU1H92C6tclA4aIWiBzOou+p38JdvnYuMVEtnSsS9rsJdRsjMn/G3r6Oibi8xnHKhNdQNzjrsp+lJyQd0PTDFTPGa8Gech2NvNonJwNrwJlrahvb3Q//wc0gD3CVh0hzGMv9lKyiyHALVlnjpTQY+vnarczF/HxkLlBQ/oBxS2XXDCnJCGC/XWNGGuJ1MGLniopQ2g2UTnn8bo8nsxIIPeTU6dSOe83w/rLy1Uh0B+MrWLNisbjM2QHBlbY7vl0wL7lFvmVhUZougS55SnquDXf3BOBpkMU/jHrW6ByvHL2/CgXU7vIh6H7njtQW5J6T8keCTiauQVVG7wk2eNYBz4u8nogjWyOAX826o1YPf/aoSW9CABoaEJM=
    -
      secure: CDCQzlxuVfZa8jyNgwvch5RID5EHal03TLE10uR2RgoC1+8NSpv85qehjRSojTwdmmOovrXXur6Ew6dIQi6Xg/6kzJ1J7xUWP52nElXdZ4jWIA3lLizC3yze+wXlaq7R8gCwqnao9id3Z0RZ2PdMR5oTs4oD/T56HsLEJDZVzfqhOtG12nPxa6tXU9GS+fB5R3qh2pV3gZOOQI07dv+y5zFMmvnUewISUW/WYkOXVbj2dfoUjJ8CV/goZhMmKoh5n2QKR+QJko1JXfNgjCH+rHOO4NR9xDASBHBE7EAZzrJwo1Gzkv+Ge5bxSrfLVBzYJLjE06dDbElAkf6ZdkDO1H5n3aYfHQ3dvP1zqciOnUe9uf7gdm7Pqb4nFjSho4YwE4k99t0YbwF1B0sOnEbMQjjzRyxdDrtnkYSChWMd9S9TTTyGOm8PI1ZavawPgGn1hdI4q41UT4Vil6zty6XXvLqdv2fij4/4JSG5tNgftNIq/OVyCs6uUAwRiyLMVtVm6F0J/PNxaCylB88DV2xootVnCFwsVaS5uweGu99kIy2rNdy8w2+945UECt+K4x03JEOSCdMqJZFJDeAWBxpW9T0Wgq0wcAqthgvcaSW7ftL/4FLHzzCjZDzXGAf/q4ReOK9PblSrNuky3IguEdQCpKzHfJLZ9my0nOkvEOMiN6I=
install: true
language: java

before_install:
  - "openssl aes-256-cbc -K $encrypted_92de4acbdbc9_key -iv $encrypted_92de4acbdbc9_iv -in devops-2020-295414-205a969fb1df.json.enc -out devops-2020-295414-205a969fb1df.json -d"
  - "curl https://sdk.cloud.google.com | bash > /dev/null"
  - "source \"$HOME/google-cloud-sdk/path.bash.inc\""
  - "gcloud auth activate-service-account --key-file=devops-2020-295414-205a969fb1df.json"
  - "gcloud auth configure-docker"
  - "gcloud config set project \"${GCP_PROJECT_ID}\""
  - "gcloud components install beta"
  - - "chmod +x mvnw"
script:
  - |-
    set -ex;
    docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
    docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
    set +x
services:
  - docker
