#!/bin/bash
docker build . --tag devops --build-arg JAR_FILE=./target/demo-0.0.1-SNAPSHOT.jar
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag kamranaliiqbal/devops
docker push kamranaliiqbal/devops