#!/bin/bash
docker build . --tag devops-exam --build-arg JAR_FILE=./target/devops-exam-0.0.1-SNAPSHOT.jar
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag devops-exam kamranaliiqbal/devops-exam
docker push kamranaliiqbal/devops-exam